name: My deploy

on:
  [push]

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      image_name: registry.digitalocean.com/laravel-registry/devops-php:${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      - name: Build and push
        run: |
          docker build -t registry.digitalocean.com/laravel-registry/devops-php:${{ github.sha }} -f php.Dockerfile .
          docker login registry.digitalocean.com -u student1223@tuit.uz -p ${{ secrets.REGISTRY_TOKEN }}
          docker push registry.digitalocean.com/laravel-registry/devops-php:${{ github.sha }}    

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "."
          target: /opt/laravel

      - name: Run app
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
              cd /opt/laravel
              yq -i '.services.php.image"${{ needs.build.outputs.image_name }}"' docker-compose.yaml
              docker compose up -d