name: django-deploy.yml
on:
  push:
    branches:
      - main
    paths:
      - './django-app/*'
      - '.github/workflows/django-deploy.yml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10.12'

      - name: pip install packages
        working-directory: ./django-app/mydjangoapp
        run: |
          python3 -m venv env
          source env/bin/activate
          pip3 install --upgrade pip
          pip3 install -r requirements.txt

      - name: Deploy
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "django-app/mydjangoapp/*"
          target: '/opt/'

      - name: Run app
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: systemctl restart mydjangoapp-gunicorn.service