name: django-deploy.yml
on:
  push:
    branches:
      - main
    paths:
      - './django-app/*'
      - '.github/workflows/django-deploy.yml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "django-app/mydjangoapp/*"
          target: '/opt/'

      - name: Run app
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /opt/django-app/mydjangoapp
            python3 -m venv env
            source env/bin/activate
            pip3 install --upgrade pip
            pip3 install -r requirements.txt
            python3 manage.py migrate
            systemctl restart mydjangoapp-gunicorn.service